const PostActionsTypes = {
	//RESPONSE HANDLING
	POST_SUCCESS_HANDLING: 'POST_SUCCESS_HANDLING',
	POST_ERROR_HANDLING: 'POST_ERROR_HANDLING',
	POST_INFO_HANDLING: 'POST_INFO_HANDLING',
	POST_WARNING_HANDLING: 'POST_WARNING_HANDLING',

	//CREATE POST
	POST_CREATION_START: 'POST_CREATION_START',
	POST_CREATION_SUCCESS: 'POST_CREATION_SUCCESS',

	//SAVE CONTENT
	SAVE_POST_CONTENT_START: 'SAVE_POST_CONTENT_START',
	SAVE_POST_CONTENT_SUCCESS: 'SAVE_POST_CONTENT_SUCCESS'
};
export default PostActionsTypes;
