const RootActionsTypes = {
	//GENRIC RESPONSE HANDLING
	SUCCESS_HANDLING: 'SUCCESS_HANDLING',
	ERROR_HANDLING: 'ERROR_HANDLING',
	INFO_HANDLING: 'INFO_HANDLING',
	WARNING_HANDLING: 'WARNING_HANDLING'
};
export default RootActionsTypes;
