const UserActionTypes = {
	LOCAL_SIGN_IN_START: 'LOCAL_SIGN_IN_START',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
	SIGN_OUT_START: 'SIGN_OUT_START',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
	SIGN_UP_START: 'SIGN_UP_START',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
	GET_CURRENT_USER: 'GET_CURRENT_USER',
	USER_VERIFICATION_START: 'USER_VERIFICATION_START',
	USER_VERIFICATION_SUCCESS: 'USER_VERIFICATION_SUCCESS',
	USER_VERIFICATION_FAILURE: 'USER_VERIFICATION_FAILURE',
	VERIFICATION_CODE_RESEND_START: 'VERIFICATION_CODE_RESEND_START',
	VERIFICATION_CODE_RESEND_FAILURE: 'VERIFICATION_CODE_RESEND_FAILURE'
};

export default UserActionTypes;
