const UserActionTypes = {
	LOCAL_SIGN_IN_START: 'LOCAL_SIGN_IN_START',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
	SIGN_OUT_START: 'SIGN_OUT_START',
	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
	SIGN_UP_START: 'SIGN_UP_START',
	SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
	SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
	GET_CURRENT_USER: 'GET_CURRENT_USER'
};

export default UserActionTypes;
