const AppActionTypes = {
	SHOW_SEARCH_BAR: 'SHOW_SEARCH_BAR',
	HIDE_SEARCH_BAR: 'HIDE_SEARCH_BAR',
	SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
	TOGGLE_THEME: 'TOGGLE_THEME'
};

export default AppActionTypes;
