const CategoriesActionTypes = {
	//FETCH CATEGORIES
	CATEGORIES_FETCH_START: 'CATEGORIES_FETCHING_START',
	CATEGORIES_FETCH_SUCCESS: 'CATEGORIES_FETCH_SUCCESS',
	CATEGORIES_FETCH_FAILURE: 'CATEGORIES_FETCH_FAILURE',
	CATEGORIES_CATCH_ERROR: 'CATEGORIES_CATCH_ERROR'
};

export default CategoriesActionTypes;
